// Auto-generated by Circular Pixel Art Generator
#include <stdint.h>

#define PAT_RADIUS  5
#define PAT_ANGLES  4

const uint8_t pattern[PAT_ANGLES][PAT_RADIUS][3] = {
  {  // theta 0
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83}
  },
  {  // theta 1
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83}
  },
  {  // theta 2
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83}
  },
  {  // theta 3
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83},
    {179, 0, 83}
  }
};
