// Auto-generated by Circular Pixel Art Generator
#include <stdint.h>

#define PAT_RADIUS      5
#define PAT_ANGLES_MAX 72

const uint8_t used_angles = 4;

const uint8_t pattern[PAT_ANGLES_MAX][PAT_RADIUS][3] = {
  {  // theta 0
    {31, 102, 0},
    {31, 102, 0},
    {31, 102, 0},
    {31, 102, 0},
    {102, 0, 0}
  },
  {  // theta 1
    {31, 102, 0},
    {31, 102, 0},
    {31, 102, 0},
    {102, 0, 0},
    {31, 102, 0}
  },
  {  // theta 2
    {31, 102, 0},
    {31, 102, 0},
    {102, 0, 0},
    {31, 102, 0},
    {31, 102, 0}
  },
  {  // theta 3
    {102, 0, 0},
    {102, 0, 0},
    {31, 102, 0},
    {31, 102, 0},
    {31, 102, 0}
  }
};
